name = "up-blogs-1"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
WORKER_URL = "https://up-blogs-1.micaiah-tasks.workers.dev"

[[kv_namespaces]]
binding = "BLOGS"
id = "" # Will be filled in after creating KV
